//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.megadevs.nostradamus.nostranfc;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class Prefs_
    extends SharedPreferencesHelper
{


    public Prefs_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public Prefs_.PrefsEditor_ edit() {
        return new Prefs_.PrefsEditor_(getSharedPreferences());
    }

    public StringPrefField role() {
        return stringField("role", "");
    }

    public final static class PrefsEditor_
        extends EditorHelper<Prefs_.PrefsEditor_>
    {


        PrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<Prefs_.PrefsEditor_> role() {
            return stringField("role");
        }

    }

}
